#!/usr/bin/env bash
# shellcheck disable=SC1090
# ==================================================================
# bb-loader
# ==================================================================
# Release Manager - Automated Release & Deployment Bot
#
# File:         bb-loader
# Author:       Ragdata
# Date:         13/01/2023
# License:      MIT License
# Copyright:    Copyright © 2022-2023 Darren Poulton (Ragdata)
# ==================================================================

BB_FILES=(
    "bb-common/bb-ansi"
    "bb-common/bb-regex"
    "bb-common/bb-functions/arrays.func"
    "bb-common/bb-functions/files.func"
    "bb-common/bb-functions/stdout.func"
    "bb-common/bb-functions/env.func"
    "bb-common/bb-functions/strings.func"
    "bb-common/bb-functions/utility.func"
)

for i in "${!BB_FILES[@]}"
do
    if [[ -f "$BB_LIB/${BB_FILES[$i]}" ]]; then
        source "$BB_LIB/${BB_FILES[$i]}"
    else
        echo "Bash-Bits :: File '${BB_FILES[$i]}' Not Found!"
        exit 1
    fi
done
