name: CI

on:
    pull_request:
        branches:
            - develop
            - master
    push:
        branches:
            - develop
            - master

jobs:
    shellcheck:
        runs-on: ubuntu-latest
        env:
            PWD: "."
            RM_LIB: "src/lib"
            RM_BIN: "src/bin"
            ETC: "src/etc"
            RM_OPT: "."
            RM_LOG: "log"

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Lint
              uses: azohra/shell-linter@latest
              with:
                  exclude-paths: "log" "inc" "cfg" "src/etc/release" "src/etc/release-action"
