name: CI

on:
    pull_request:
        branches:
            - develop
            - master
    push:
        branches:
            - develop
            - master

jobs:
    lint:
        name: Linter
        uses: ragdata/workflows/.github/workflows/linter.yml@master

    shellcheck:
        name: Shellcheck
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run Shellcheck
              uses: ragdata/workflows/.github/actions/shellcheck/action.yml@master
